[package]
name = "oxide64"
version = "0.1.0"
authors = ["dignifiedquire <dignifiedquire@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
failure = "*"
byteorder = "*"

[dev-dependencies]
glob = "^0.2"